application: effmeme
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico 
  upload: images/favicon.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images

- url: .*
  script: bindings.py

builtins:
- remote_api: on

